config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'

  resources :lists, only: [:index, :new, :create, :show] do
    resources :bookmarks, only: [:index, :new, :create]
  end
    resources :bookmarks, only: :destroy
end

  # get 'lists', to: 'lists#index'
  # get 'lists/new', to: 'lists#new', as: 'new'
  # get 'lists/:id', to: 'lists#show'
  # post 'lists', to: 'lists#create'

  # get 'lists/:id/bookmarks', to: 'bookmarks#index'
  # get 'lists/:id/bookmarks/new' to: 'bookmarks#new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: 'Movie is already in list' }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:show, :create, :new]
  before_action :set_bookmark, only: [:destroy]

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
      if @bookmark.save
        redirect_to list_path(@list)
      else
        render :new
      end
  end

  def show
  end

  def destroy
    @bookmark.destroy
    redirect_to root_path
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-3">
  <img alt="alttext" class="logo" src="/assets/film.png" width= 30px height=30px>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/lists">Home</a>
        </li>
    </ul>
  </div>
</div>

<h1>Bookmarks</h1>

<div class="row my-2">
    <% @bookmarks.each do |bookmark| %>
      <div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
        <div class="bg-white rounded shadow h-100">
          <div class="p-3 rounded-bottom d-flex flex-column">
           <%= image_tag bookmark.movie.poster_url, alt: bookmark.movie.title, class: 'movie-img rounded-top' %>
            <strong><%= bookmark.movie.title %> <span class="text-muted font-weight-normal">• <%= bookmark.movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
            <small class="text-muted"><%= bookmark.movie.overview %></small>
            <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
                <i class="fas fa-quote-left mr-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
              </div>
              <small class="text-right flex-shrink-0">
              <%= link_to 'Delete Bookmark', bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{bookmark.movie.title} from your #{bookmark.list.name} list"}, class: 'text-danger' %></small>
              <%= link_to 'Go back to all lists', lists_path %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/bookmarks/new.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-3">
  <img alt="alttext" class="logo" src="/assets/film.png" width= 30px height=30px>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/lists">Home</a>
        </li>
    </ul>
  </div>
</div>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <p><span data-controller="typed-js"></span></p>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-3">
  <img alt="alttext" class="logo" src="/assets/film.png" width= 30px height=30px>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/lists">Home</a>
        </li>
    </ul>
  </div>
</div>

<div class= "m-3">
<h1>List of movie genres</h1>
<p><% @lists.each do |list| %>
<p><%= link_to "#{list.name}", list_path(list) %></p>
<% end %>

<%= cl_image_tag("twlyih46ewapewpvwn48",
      width: 400, height: 300, crop: :fill) %>

<!-- for face detection -->
<%= cl_image_tag("rgrfnprmx3pnwblyhnb0",
      width: 150, height: 150, crop: :thumb, gravity: :face) %>

<button class="btn btn-info"><%= link_to "Create new", new_list_path %></button>
</div>

app/views/lists/new.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-3">
  <img alt="alttext" class="logo" src="/assets/film.png" width= 30px height=30px>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/lists">Home</a>
        </li>
    </ul>
  </div>
</div>

<h1>Create new list</h1>
<%= render "form", list: @list %>

app/views/lists/show.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-3">
  <img alt="alttext" class="logo" src="/assets/film.png" width= 30px height=30px>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/lists">Home</a>
        </li>
    </ul>
  </div>
</div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1508020963102-c6c723be5764?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80);">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>

<%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>

<div class="card-category"
  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>')"
>
  Cool article
</div>

<div class= "m-3">

<button class="btn btn-warning"><%= link_to "See Lists", lists_path %></button>
<button class="btn btn-warning"><%= link_to "Add Bookmark", new_list_bookmark_path(@list) %></button>
<button class="btn btn-warning"><%= link_to "See All Bookmarks", list_bookmarks_path(@list) %></button>
</div>